# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultdataset',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultdataset',
            name='capital_gain',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultdataset',
            name='capital_loss',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultdataset',
            name='education_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultdataset',
            name='fnlwgt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultdataset',
            name='hours_per_week',
            field=models.CharField(max_length=20),
        ),
    ]
